lib/measure_matter_server_web/router.ex
defmodule MeasureMatterServerWeb.Router do
  use MeasureMatterServerWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "text", "json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MeasureMatterServerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MeasureMatterServerWeb.Plugs.Locale, "es"
    plug :fetch_current_user
    plug :fetch_current_cart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MeasureMatterServerWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/baseitems", BaseItemController, :index
    get "/baseitems/:sku", BaseItemController, :show
    resources "/products", ProductController
    resources "/cart_items", CartItemController, only: [:create, :delete]

    get "/cart", CartController, :show
    put "/cart", CartController, :update
    resources "/orders", OrderController, only: [:create, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MeasureMatterServerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MeasureMatterServerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  defp fetch_current_user(conn, _) do
    if user_uuid = get_session(conn, :current_uuid) do
      assign(conn, :current_uuid, user_uuid)
    else
      new_uuid = Ecto.UUID.generate()

      conn
      |> assign(:current_uuid, new_uuid)
      |> put_session(:current_uuid, new_uuid)
    end
  end

  alias MeasureMatterServer.ShoppingCart
  defp fetch_current_cart(conn, _opt) do
    if cart = MeasureMatterServer.ShoppingCart.get_cart_by_user_uuid(conn.assigns.current_uuid) do
      assign(conn, :cart, cart)
    else
      {:ok, new_cart} = ShoppingCart.create_cart(conn.assigns.current_uuid)
      assign(conn, :cart, new_cart)
    end
  end



end

lib/measure_matter_server/catalog/product.ex
defmodule MeasureMatterServer.Catalog.Product do
  use Ecto.Schema
  import Ecto.Changeset
  alias MeasureMatterServer.Catalog.Category

  schema "products" do
    field :description, :string
    field :price, :decimal
    field :title, :string
    field :views, :integer

    many_to_many :categories, Category, join_through: "product_categories", on_replace: :delete

    timestamps()
  end

  @doc false
  def changeset(product, attrs) do
    product
    |> cast(attrs, [:title, :description, :price, :views])
    |> validate_required([:title, :description, :price, :views])
  end
end

lib/measure_matter_server_web/controllers/product_controller.ex
defmodule MeasureMatterServerWeb.ProductController do
  use MeasureMatterServerWeb, :controller

  alias MeasureMatterServer.Catalog
  alias MeasureMatterServer.Catalog.Product

  def index(conn, _params) do
    products = Catalog.list_products()
    render(conn, "index.html", products: products)
  end

  def new(conn, _params) do
    changeset = Catalog.change_product(%Product{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => product_params}) do
    case Catalog.create_product(product_params) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: Routes.product_path(conn, :show, product))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    product = id
    |> Catalog.get_product!()
    |> Catalog.increment_product_views()

    render(conn, "show.html", product: product)
  end

  def edit(conn, %{"id" => id}) do
    product = Catalog.get_product!(id)
    changeset = Catalog.change_product(product)
    render(conn, "edit.html", product: product, changeset: changeset)
  end

  def update(conn, %{"id" => id, "product" => product_params}) do
    product = Catalog.get_product!(id)

    case Catalog.update_product(product, product_params) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: Routes.product_path(conn, :show, product))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", product: product, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    product = Catalog.get_product!(id)
    {:ok, _product} = Catalog.delete_product(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: Routes.product_path(conn, :index))
  end
end

lib/measure_matter_server_web/views/product_view.ex
defmodule MeasureMatterServerWeb.ProductView do
  use MeasureMatterServerWeb, :view
  def category_select(f, changeset) do
    existing_ids = changeset |> Ecto.Changeset.get_change(:categories, []) |> Enum.map(& &1.data.id)

    category_opts =
      for cat <- MeasureMatterServer.Catalog.list_categories(), do:
        [key: cat.title, value: cat.id, selected: cat.id in existing_ids]

    multiple_select(f, :category_ids, category_opts)
  end
end

lib/measure_matter_server_web/templates/product/edit.html.heex
<h1>Edit Product</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.product_path(@conn, :update, @product)) %>

<span><%= link "Back", to: Routes.product_path(@conn, :index) %></span>

lib/measure_matter_server_web/templates/product/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :price %>
  <%= number_input f, :price, step: "any" %>
  <%= error_tag f, :price %>

  <%= label f, :views %>
  <%= number_input f, :views %>
  <%= error_tag f, :views %>
  
  <%= category_select f, @changeset %>
  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/measure_matter_server_web/templates/product/index.html.heex
<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Views</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.views %></td>

      <td>
        <span><%= link "Show", to: Routes.product_path(@conn, :show, product) %></span>
        <span><%= link "Edit", to: Routes.product_path(@conn, :edit, product) %></span>
        <span><%= link "Delete", to: Routes.product_path(@conn, :delete, product), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Product", to: Routes.product_path(@conn, :new) %></span>

lib/measure_matter_server_web/templates/product/new.html.heex
<h1>New Product</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.product_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.product_path(@conn, :index) %></span>

lib/measure_matter_server_web/templates/product/show.html.heex
<h1>Show Product</h1>
<%=link "Add To Cart", to: Routes.cart_item_path(@conn, :create, product_id: @product.id), method: :post %>
<ul>

  <li>
    <strong>Title:</strong>
    <%= @product.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @product.description %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= @product.price %>
  </li>

  <li>
    <strong>Views:</strong>
    <%= @product.views %>
  </li>

  <li>
    <strong>Categories:</strong>
    <%= for cat <- @product.categories do %>
      <br>
      <%= cat.title %>
    <% end %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.product_path(@conn, :edit, @product) %></span> |
<span><%= link "Back", to: Routes.product_path(@conn, :index) %></span>